version: "3.5"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-django/base
    command: python manage.py runserver 0.0.0.0:5000
    env_file:
      - env/local.env
    ports:
      - 5000:5000
    volumes:
      - .:/src:delegated
    restart: unless-stopped

  cache:
    image: redis:alpine
    ports:
      - 6379:6379

  database:
    image: amazon/dynamodb-local:latest
    env_file:
      - env/local.env
    ports:
      - 8000:8000

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: api