version: "3.5"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-django/base
    command: flask run --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    restart: unless-stopped

  cache:
    image: redis:alpine
    ports:
      - 6379:6379

  database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
